# Generated by Django 5.2.1 on 2025-05-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutletForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('outlet_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('max_budget', models.BigIntegerField()),
                ('min_size', models.IntegerField()),
            ],
        ),
    ]
