# Generated by Django 5.2.1 on 2025-06-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photographer', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('is_onsite', models.BooleanField(default=True)),
                ('photos_covered', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
