# Generated by Django 5.2.1 on 2025-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_sqft', models.PositiveIntegerField()),
                ('property_type', models.CharField(max_length=100)),
                ('year_built', models.IntegerField()),
                ('monthly_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_rental', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_of_property', models.CharField(max_length=100)),
                ('features', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='listing_thumbs/')),
            ],
        ),
    ]
