# Generated by Django 5.2.1 on 2025-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('category_image', models.URLField()),
                ('price', models.BigIntegerField()),
                ('price_format', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('premium_property', models.BooleanField(default=False)),
                ('price_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('property_image', models.URLField()),
                ('is_favourite', models.BooleanField(default=False)),
                ('property_for', models.IntegerField(default=1)),
                ('advertisement_property', models.BooleanField(blank=True, null=True)),
                ('advertisement_property_date', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('sqft', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
