# Generated by Django 5.2.1 on 2025-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_property_age_of_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenity',
            name='value',
            field=models.JSONField(),
        ),
    ]
