# Generated by Django 5.2.1 on 2025-06-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_propertyamenity_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='api.customer'),
        ),
    ]
