# Generated by Django 5.2.1 on 2025-06-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_property_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.IntegerField(choices=[(0, 'Rent'), (1, 'Sale')], default=1),
        ),
    ]
