# Generated by Django 5.2.1 on 2025-06-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_property_property_for'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
