# Generated by Django 5.2.1 on 2025-06-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.TimeField()),
                ('status', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('city_id', models.IntegerField()),
                ('total_review', models.IntegerField(default=0)),
                ('total_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_favourite', models.BooleanField(default=False)),
                ('attchment_extension', models.BooleanField(default=True)),
                ('is_slot', models.BooleanField(default=False)),
                ('visit_type', models.CharField(max_length=50)),
                ('is_enable_advance_payment', models.BooleanField(default=False)),
                ('advance_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('moq', models.IntegerField()),
                ('attchments', models.ManyToManyField(to='api.attachment')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provider')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecategory')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicesubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slot', models.JSONField(default=list)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.service')),
            ],
        ),
    ]
