# Generated by Django 5.2.1 on 2025-07-02 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_customerservice_provider_address_provider_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provideraddress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceAddressMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_address_mappings', to='api.provideraddress')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_address_mappings', to='api.service')),
            ],
        ),
    ]
