# Generated by Django 5.2.1 on 2025-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_provideraddress_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='city',
        ),
        migrations.RemoveField(
            model_name='service',
            name='city_id',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
