# Generated by Django 5.2.1 on 2025-07-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_provider_city_remove_service_city_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='about',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='latitude',
            new_name='handyman_type',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='longitude',
            new_name='login_type',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_in_city', to='api.city'),
        ),
        migrations.AddField(
            model_name='provider',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='country_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='handyman_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='handyman_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='provider',
            name='handymantype_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='isHandymanAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_verify_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='known_languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_notification_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='providers_service_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='provider',
            name='providertype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='providertype_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='service_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_with_this_service_address', to='api.provideraddress'),
        ),
        migrations.AddField(
            model_name='provider',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='state_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='time_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='total_service_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='total_services_booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='why_choose_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
