# Generated by Django 5.2.1 on 2025-07-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_about_provider_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefaq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceaddressmapping',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_addresses', to='api.service'),
        ),
    ]
