# Generated by Django 5.2.1 on 2025-07-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_servicefaq_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceaddon',
            old_name='image',
            new_name='serviceaddon_image',
        ),
    ]
